//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Det_1500Form
    {
        public long RowNum { get; set; }
        public Nullable<long> ReferenceNo { get; set; }
        public string ClientCode { get; set; }
        public string BillNo { get; set; }
        public string BoxNo1Medicare { get; set; }
        public string BoxNo1Medicaid { get; set; }
        public string BoxNo1Tricare { get; set; }
        public string BoxNo1CHAMPVA { get; set; }
        public string BoxNo1Group { get; set; }
        public string BoxNo1FECA { get; set; }
        public string BoxNo1Other { get; set; }
        public string BoxNo1a { get; set; }
        public string BoxNo2 { get; set; }
        public string BoxNo3DOBMM { get; set; }
        public string BoxNo3DOBDD { get; set; }
        public string BoxNo3DOBYY { get; set; }
        public string BoxNo3SexMale { get; set; }
        public string BoxNo3SexFemale { get; set; }
        public string BoxNo4 { get; set; }
        public string BoxNo5Add { get; set; }
        public string BoxNo5City { get; set; }
        public string BoxNo5Sta { get; set; }
        public string BoxNo5Zip { get; set; }
        public string BoxNo5Area { get; set; }
        public string BoxNo5Phone { get; set; }
        public string BoxNo6Self { get; set; }
        public string BoxNo6Spouse { get; set; }
        public string BoxNo6Child { get; set; }
        public string BoxNo6Other { get; set; }
        public string BoxNo7Add { get; set; }
        public string BoxNo7City { get; set; }
        public string BoxNo7Sta { get; set; }
        public string BoxNo7Zip { get; set; }
        public string BoxNo7Area { get; set; }
        public string BoxNo7Phone { get; set; }
        public string BoxNo8Single { get; set; }
        public string BoxNo8Married { get; set; }
        public string BoxNo8Other { get; set; }
        public string BoxNo8Employed { get; set; }
        public string BoxNo8FullTimeStudent { get; set; }
        public string BoxNo8PartTimeStudent { get; set; }
        public Nullable<int> BoxNo9 { get; set; }
        public string BoxNo9a { get; set; }
        public string BoxNo9bDOBMM { get; set; }
        public string BoxNo9bDOBDD { get; set; }
        public string BoxNo9bDOBYY { get; set; }
        public Nullable<int> BoxNo9bSexMale { get; set; }
        public Nullable<int> BoxNo9bSexFemale { get; set; }
        public Nullable<int> BoxNo9c { get; set; }
        public string BoxNo9d { get; set; }
        public string BoxNo10aYes { get; set; }
        public string BoxNo10aNo { get; set; }
        public string BoxNo10bYes { get; set; }
        public string BoxNo10bNo { get; set; }
        public string BoxNo10bPlace { get; set; }
        public string BoxNo10cYes { get; set; }
        public string BoxNo10cNo { get; set; }
        public string BoxNo10d { get; set; }
        public string BoxNo11 { get; set; }
        public string BoxNo11aDOBMM { get; set; }
        public string BoxNo11aDOBDD { get; set; }
        public string BoxNo11aDOBYY { get; set; }
        public string BoxNo11aSexMale { get; set; }
        public string BoxNo11aSexFemale { get; set; }
        public Nullable<int> BoxNo11b { get; set; }
        public string BoxNo11c { get; set; }
        public string BoxNo11dYes { get; set; }
        public string BoxNo11dNo { get; set; }
        public string BoxNo12Sign { get; set; }
        public string BoxNo12Date { get; set; }
        public string BoxNo13Sign { get; set; }
        public string BoxNo14MM { get; set; }
        public string BoxNo14DD { get; set; }
        public string BoxNo14YY { get; set; }
        public string BoxNo15MM { get; set; }
        public string BoxNo15DD { get; set; }
        public string BoxNo15YY { get; set; }
        public string BoxNo16FromMM { get; set; }
        public string BoxNo16FromDD { get; set; }
        public string BoxNo16FromYY { get; set; }
        public string BoxNo16ToMM { get; set; }
        public string BoxNo16ToDD { get; set; }
        public string BoxNo16ToYY { get; set; }
        public string BoxNo17 { get; set; }
        public string BoxNo17A { get; set; }
        public string BoxNo17NPI { get; set; }
        public string BoxNo18FromMM { get; set; }
        public string BoxNo18FromDD { get; set; }
        public string BoxNo18FromYY { get; set; }
        public string BoxNo18ToMM { get; set; }
        public string BoxNo18ToDD { get; set; }
        public string BoxNo18ToYY { get; set; }
        public string BoxNo19 { get; set; }
        public Nullable<int> BoxNo20aYes { get; set; }
        public string BoxNo20aNo { get; set; }
        public Nullable<int> BoxNo20bChargesA { get; set; }
        public Nullable<int> BoxNo20bChargesB { get; set; }
        public string BoxNo21IcdCode1 { get; set; }
        public string BoxNo21IcdCode2 { get; set; }
        public string BoxNo21IcdCode3 { get; set; }
        public string BoxNo21IcdCode4 { get; set; }
        public string BoxNo21IcdCode5 { get; set; }
        public string BoxNo21IcdCode6 { get; set; }
        public Nullable<int> BoxNo22Code { get; set; }
        public Nullable<int> BoxNo22RefNo { get; set; }
        public string BoxNo23 { get; set; }
        public string BoxNo24AFromMM { get; set; }
        public string BoxNo24AFromDD { get; set; }
        public string BoxNo24AFromYY { get; set; }
        public string BoxNo24AToMM { get; set; }
        public string BoxNo24AToDD { get; set; }
        public string BoxNo24AToYY { get; set; }
        public string BoxNo24B { get; set; }
        public Nullable<int> BoxNo24C { get; set; }
        public string BoxNo24Code { get; set; }
        public string BoxNo24Mod1 { get; set; }
        public string BoxNo24Mod2 { get; set; }
        public string BoxNo24Mod3 { get; set; }
        public string BoxNo24Mod4 { get; set; }
        public string BoxNo24E { get; set; }
        public Nullable<double> BilledAmt { get; set; }
        public string BoxNo24VisitDtOhio { get; set; }
        public string BilledDateOhio { get; set; }
        public string BoxNo24FOh { get; set; }
        public Nullable<int> BoxNo24F { get; set; }
        public string BoxNo24FDec { get; set; }
        public string BoxNo24G { get; set; }
        public Nullable<int> BoxNo24H { get; set; }
        public string BoxNo24I { get; set; }
        public string BoxNo24Ja { get; set; }
        public string BoxNo24JNPI { get; set; }
        public string BoxNo25a { get; set; }
        public string BoxNo25bSSN { get; set; }
        public string BoxNo25bEIN { get; set; }
        public string BoxNo26 { get; set; }
        public string BoxNo27Yes { get; set; }
        public string BoxNo27No { get; set; }
        public string BoxNo31a { get; set; }
        public string BoxNo31b { get; set; }
        public string BoxNo32a { get; set; }
        public string BoxNo32b { get; set; }
        public string BoxNo32c { get; set; }
        public string BoxNo32aNPI { get; set; }
        public string BoxNo33a { get; set; }
        public string BoxNo33b { get; set; }
        public string BoxNo33c { get; set; }
        public string BoxNo33d { get; set; }
        public string BoxNo33e { get; set; }
        public string BoxNo33F { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string InsuranceFlag { get; set; }
        public Nullable<bool> PrintLine { get; set; }
        public Nullable<int> Sno { get; set; }
        public string InsuranceCode { get; set; }
        public string InsuranceName { get; set; }
        public string InsAddress1 { get; set; }
        public string InsHead2 { get; set; }
        public string InsHead3 { get; set; }
        public string InsCityName { get; set; }
        public string InsStateCode { get; set; }
        public string InsZipCode { get; set; }
        public Nullable<System.DateTime> FromVisitDate { get; set; }
        public string PatLastName { get; set; }
        public string PatFirstName { get; set; }
        public string ProviderAddress { get; set; }
        public string ProCity { get; set; }
        public string ProState { get; set; }
        public string ProZip { get; set; }
        public string MedicalRecordNo { get; set; }
        public string ProviderServiceCode { get; set; }
        public Nullable<System.DateTime> BilledDate { get; set; }
        public string GroupID { get; set; }
        public string AllowedAmt { get; set; }
        public string Deductable { get; set; }
        public string CoIns { get; set; }
        public string DatePaidByMedicar { get; set; }
        public string Insamount { get; set; }
        public string InsPayment { get; set; }
        public string InsHCFABox29 { get; set; }
        public string InsHCFABox30 { get; set; }
    
        public virtual Bill_Mst_1500Form Bill_Mst_1500Form { get; set; }
    }
}
