//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Mst_1500Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill_Mst_1500Form()
        {
            this.Bill_Det_1500Form = new HashSet<Bill_Det_1500Form>();
            this.Bill_Det_EOBFile = new HashSet<Bill_Det_EOBFile>();
        }
    
        public long ReferenceNo { get; set; }
        public string ClientCode { get; set; }
        public string BillNo { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.DateTime BillDate { get; set; }
        public string PatientCode { get; set; }
        public string PatientName { get; set; }
        public string Charges { get; set; }
        public string InsBalance { get; set; }
        public string InsuranceName { get; set; }
        public string InsuranceCode { get; set; }
        public string InsuranceFlag { get; set; }
        public string BillProvider { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int Status { get; set; }
        public string CompleteBy { get; set; }
        public string CompleteDate { get; set; }
        public string ClosedBy { get; set; }
        public string ClosedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Queue { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCityCode { get; set; }
        public string BillZipCode { get; set; }
        public string BillStateCode { get; set; }
        public string BillCityName { get; set; }
        public string BillStateName { get; set; }
        public string ProviderTitle { get; set; }
        public string InsAddress1 { get; set; }
        public string InsAddress2 { get; set; }
        public string InsCityCode { get; set; }
        public string InsCityName { get; set; }
        public string InsStateCode { get; set; }
        public string InsStateName { get; set; }
        public string InsZipCode { get; set; }
        public Nullable<int> visitno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Det_1500Form> Bill_Det_1500Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Det_EOBFile> Bill_Det_EOBFile { get; set; }
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster { get; set; }
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster1 { get; set; }
    }
}
