//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Det_EOBFile
    {
        public long RowNum { get; set; }
        public Nullable<long> ReferenceNo { get; set; }
        public string ClientCode { get; set; }
        public string BillNo { get; set; }
        public string BillPostId { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string ChequeNo { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string EOBFileName { get; set; }
        public string LocalEOBFile { get; set; }
        public Nullable<int> EOBPageNO { get; set; }
    
        public virtual Bill_Mst_1500Form Bill_Mst_1500Form { get; set; }
    }
}
