//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_Requirements
    {
        public long RowNum { get; set; }
        public string requirementId { get; set; }
        public string ProductCode { get; set; }
        public string ClientCode { get; set; }
        public string Description { get; set; }
        public string ScreenCode { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Title { get; set; }
        public string IssueNo { get; set; }
        public string Version { get; set; }
        public string IssueType { get; set; }
        public string Priority { get; set; }
        public string ClientVersion { get; set; }
        public string MovedBy { get; set; }
        public Nullable<System.DateTime> MovedDate { get; set; }
        public string AssignTo { get; set; }
        public string ResolverTime { get; set; }
        public string UnitTesterTime { get; set; }
        public string TesterTime { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TaskNo { get; set; }
        public Nullable<System.DateTime> EmailDate { get; set; }
        public Nullable<bool> EmailReply { get; set; }
    }
}
