//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_Client_EmailID
    {
        public string ProductCode { get; set; }
        public string ClientCode { get; set; }
        public string EmailID { get; set; }
        public string ContactName { get; set; }
        public string Username { get; set; }
    }
}
