//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Custom_Number
    {
        public string CustPurposeID { get; set; }
        public string CustCodeFieldType1 { get; set; }
        public string CustCodeField1 { get; set; }
        public string CustCodeFieldType2 { get; set; }
        public string CustCodeField2 { get; set; }
        public string CustCodeFieldType3 { get; set; }
        public string CustCodeField3 { get; set; }
        public string CustCodeFieldType4 { get; set; }
        public string CustCodeField4 { get; set; }
        public string CustDelimeter { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Gen_Custom_Ctrl Gen_Custom_Ctrl { get; set; }
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster { get; set; }
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster1 { get; set; }
    }
}
