//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_ErrLog
    {
        public int ErrorIdentity { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserErrMsg { get; set; }
        public string ModuleName { get; set; }
        public string FunctionName { get; set; }
        public string DBErrMsg { get; set; }
        public string AddionalInfo { get; set; }
        public string ScreenID { get; set; }
        public string VersionNo { get; set; }
        public string MachineName { get; set; }
        public string MessageType { get; set; }
    
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster { get; set; }
    }
}
