//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_HowDoI
    {
        public string ProductCode { get; set; }
        public string ModuleCode { get; set; }
        public string ScreenCode { get; set; }
        public long TopicId { get; set; }
        public string TopicName { get; set; }
        public string TDescription { get; set; }
        public int TopicOrder { get; set; }
        public string DemoSourceFile { get; set; }
        public string WordFile { get; set; }
        public string VideoFile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string GifFile { get; set; }
    
        public virtual Gen_Mst_Screen Gen_Mst_Screen { get; set; }
    }
}
