//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Custom_Ctrl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gen_Custom_Ctrl()
        {
            this.Gen_Custom_Seq_Ctrl = new HashSet<Gen_Custom_Seq_Ctrl>();
        }
    
        public string CustPurposeID { get; set; }
        public string CustPurposeName { get; set; }
        public string CustTableName { get; set; }
        public string CustColName { get; set; }
        public bool VisibleStatus { get; set; }
    
        public virtual Gen_Custom_Number Gen_Custom_Number { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Custom_Seq_Ctrl> Gen_Custom_Seq_Ctrl { get; set; }
    }
}
