//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_MST_EMAILS_5312013
    {
        public long RowNum { get; set; }
        public string FromId { get; set; }
        public string ToId { get; set; }
        public string subject { get; set; }
        public string EMailStatus { get; set; }
        public string ClientCode { get; set; }
        public Nullable<System.DateTime> Receiveddate { get; set; }
        public Nullable<long> PositionID { get; set; }
    }
}
