//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_Files
    {
        public long FileID { get; set; }
        public string FileName { get; set; }
        public string FileCategory { get; set; }
        public string FileType { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public string FileTitle { get; set; }
        public string IssueNo { get; set; }
        public string ProductCode { get; set; }
        public string ModuleCode { get; set; }
        public string ScreenCode { get; set; }
        public string TabPageCode { get; set; }
        public Nullable<int> FileOrder { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<long> RowNum { get; set; }
    
        public virtual Gen_Mst_Screen Gen_Mst_Screen { get; set; }
    }
}
