//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_Employee
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Level { get; set; }
        public string Location { get; set; }
        public string Month { get; set; }
        public string NoofDaysWorked { get; set; }
        public string LeaveAvailed { get; set; }
        public string Bank { get; set; }
        public string BankAccNo { get; set; }
        public Nullable<long> BasicSalary { get; set; }
        public Nullable<long> HRA { get; set; }
        public Nullable<long> Conveyance { get; set; }
        public Nullable<long> EduAllowance { get; set; }
        public Nullable<long> OtherAllowance { get; set; }
        public Nullable<long> Incentives { get; set; }
        public string TotalGrossSalary { get; set; }
        public Nullable<long> EmpPF { get; set; }
        public Nullable<long> ESI { get; set; }
        public Nullable<long> TDS { get; set; }
        public Nullable<long> StaffAdvance { get; set; }
        public Nullable<long> Installments { get; set; }
        public Nullable<long> MobileExcess { get; set; }
        public string TotalDeductions { get; set; }
        public string NetTakeHome { get; set; }
        public string UserId { get; set; }
        public string YEAR { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string Comments { get; set; }
    }
}
