//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_MedazFollowup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gen_Mst_MedazFollowup()
        {
            this.Gen_Det_MedazFollowup = new HashSet<Gen_Det_MedazFollowup>();
        }
    
        public int RowID { get; set; }
        public string ClientCode { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserErrMsg { get; set; }
        public string ModuleName { get; set; }
        public string FunctionName { get; set; }
        public string DBErrMsg { get; set; }
        public string AddionalInfo { get; set; }
        public string ScreenID { get; set; }
        public string ScreenName { get; set; }
        public string VersionNo { get; set; }
        public string MachineName { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Det_MedazFollowup> Gen_Det_MedazFollowup { get; set; }
    }
}
