//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_Table
    {
        public string ProductCode { get; set; }
        public string TableCode { get; set; }
        public string TableName { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TableOrder { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Gen_Mst_Product Gen_Mst_Product { get; set; }
    }
}
