//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_VersionUpdate
    {
        public string ClientCode { get; set; }
        public string Product { get; set; }
        public string UserName { get; set; }
        public string OldVersion { get; set; }
        public string UpdatedVersion { get; set; }
        public string DataBaseName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> MachinesDeployed { get; set; }
        public string ExeLocation { get; set; }
        public string BeforeBackupExe { get; set; }
        public string BeforeBackupDB { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SPVersion { get; set; }
        public string UATVersion { get; set; }
        public Nullable<System.DateTime> UATVersionUpdatedate { get; set; }
        public Nullable<int> sno { get; set; }
    
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster { get; set; }
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster1 { get; set; }
    }
}
