//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_BusLogic
    {
        public int RowNum { get; set; }
        public Nullable<long> IssueNo { get; set; }
        public string Componentscode { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
        public string User { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string TechNotes { get; set; }
        public string Title { get; set; }
    }
}
