//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_ClientMachines_BACKUP
    {
        public string MachineName { get; set; }
        public string Ram { get; set; }
        public string Windowstype { get; set; }
        public string IpAddress { get; set; }
        public string AvaillableSpace { get; set; }
        public string DomainName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ClientCode { get; set; }
        public string RowNum { get; set; }
        public Nullable<bool> IsLatestUpdated { get; set; }
        public string IsLatest { get; set; }
    }
}
