//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_DET_UserPrefer
    {
        public string ControlName { get; set; }
        public string ControlValue { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster { get; set; }
    }
}
