//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gen_Mst_Screen()
        {
            this.Gen_Mst_Components = new HashSet<Gen_Mst_Components>();
            this.Gen_Mst_Files = new HashSet<Gen_Mst_Files>();
            this.Gen_Mst_HowDoI = new HashSet<Gen_Mst_HowDoI>();
            this.Gen_Mst_TabPage = new HashSet<Gen_Mst_TabPage>();
            this.IssueMasters = new HashSet<IssueMaster>();
        }
    
        public string ProductCode { get; set; }
        public string ModuleCode { get; set; }
        public string ScreenCode { get; set; }
        public string ScreenName { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ScreenOrder { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long RowNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Components> Gen_Mst_Components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Files> Gen_Mst_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_HowDoI> Gen_Mst_HowDoI { get; set; }
        public virtual Gen_Mst_Module Gen_Mst_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_TabPage> Gen_Mst_TabPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters { get; set; }
    }
}
