//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Mst_Components
    {
        public string ProductCode { get; set; }
        public string ModuleCode { get; set; }
        public string ScreenCode { get; set; }
        public string Componentscode { get; set; }
        public string ComponentsName { get; set; }
        public string TabPageCode { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ComponentsOrder { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long RowNum { get; set; }
        public string Description { get; set; }
        public string DataComments { get; set; }
        public string Datatype { get; set; }
        public Nullable<int> Length { get; set; }
        public string Tablecode { get; set; }
        public string FieldName { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Gen_Mst_Screen Gen_Mst_Screen { get; set; }
    }
}
