//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueMaster_backup_11012012
    {
        public long IssueNo { get; set; }
        public string Productcode { get; set; }
        public string ClientCode { get; set; }
        public string ModuleCode { get; set; }
        public string ScreenCode { get; set; }
        public string Tabpagecode { get; set; }
        public string Componentscode { get; set; }
        public string IssueTypeCode { get; set; }
        public string PriorityCode { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> InvestigatedDate { get; set; }
        public string InvestigatedBy { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string ResolvedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> TestedDate { get; set; }
        public string TestedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string ClosedBy { get; set; }
        public string StatusCode { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string VersionNo { get; set; }
        public string TechNotes { get; set; }
        public string IssueHours { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string UnitTestBy { get; set; }
        public Nullable<System.DateTime> UnitTestDate { get; set; }
        public string ISSUETEMPTIME { get; set; }
        public string TestInVersion { get; set; }
        public string ResolverTime { get; set; }
        public string UnitTesterTime { get; set; }
        public string TesterTime { get; set; }
        public string TestVerifiedBy { get; set; }
        public string TestVerifiedTime { get; set; }
        public Nullable<System.DateTime> TestVerifiedDate { get; set; }
        public Nullable<bool> IsDLDApproved { get; set; }
        public Nullable<int> ActualResolverTime { get; set; }
        public Nullable<int> ActualUnitTesterTime { get; set; }
        public Nullable<int> ActualTesterTime { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string ActResolverComments { get; set; }
        public string ActTesterCommentsint { get; set; }
        public string ActTesterComments { get; set; }
        public string ActUnitTesterComments { get; set; }
        public Nullable<bool> CURRENTISSUE { get; set; }
        public Nullable<int> ResolverTimeTaken { get; set; }
        public Nullable<int> TesterTimeTaken { get; set; }
        public Nullable<int> UnitTesterTimeTaken { get; set; }
        public Nullable<System.DateTime> ResolverTimeTakenStart { get; set; }
        public Nullable<System.DateTime> ResolverTimeTakenEnd { get; set; }
        public Nullable<System.DateTime> TesterTimeTakenStart { get; set; }
        public Nullable<System.DateTime> TesterTimeTakenEnd { get; set; }
        public Nullable<System.DateTime> UnitTesterTimeTakenStart { get; set; }
        public Nullable<System.DateTime> UnitTesterTimeTakenEnd { get; set; }
        public Nullable<System.DateTime> DocumentedDate { get; set; }
    }
}
