//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Testcases
    {
        public long RowNum { get; set; }
        public long IssueNo { get; set; }
        public long TestcaseID { get; set; }
        public string status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public long Testcasetype { get; set; }
        public string Description { get; set; }
    
        public virtual IssueMaster IssueMaster { get; set; }
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster { get; set; }
    }
}
