//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueMasterOld
    {
        public long IssueNo { get; set; }
        public string Title { get; set; }
        public string Client { get; set; }
        public string IssueType { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string BugInVersion { get; set; }
        public string Environment { get; set; }
        public string Screen { get; set; }
        public string Module { get; set; }
        public string CreatorComment { get; set; }
        public string InvestigatorComment { get; set; }
        public string ResolverComment { get; set; }
        public string VerifierComment { get; set; }
        public string Attachment { get; set; }
        public string IssueLink { get; set; }
        public string AssignedTo { get; set; }
        public string History { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> InvestigatedDate { get; set; }
        public string InvestigatedBy { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string ResolvedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Productcode { get; set; }
    }
}
