//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTask_Details
    {
        public string TaskNo { get; set; }
        public string Comments { get; set; }
        public string AssignedFrom { get; set; }
        public Nullable<System.DateTime> Assigneddate { get; set; }
        public long rownum { get; set; }
        public string TaskDoneBy { get; set; }
        public string IssueNo { get; set; }
    }
}
