//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights_MST_UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rights_MST_UserMaster()
        {
            this.Bill_Mst_1500Form = new HashSet<Bill_Mst_1500Form>();
            this.Bill_Mst_1500Form1 = new HashSet<Bill_Mst_1500Form>();
            this.Employee_Mst_Personal = new HashSet<Employee_Mst_Personal>();
            this.Employee_Mst_Personal1 = new HashSet<Employee_Mst_Personal>();
            this.Gen_Custom_Number = new HashSet<Gen_Custom_Number>();
            this.Gen_Custom_Number1 = new HashSet<Gen_Custom_Number>();
            this.Gen_Custom_Seq_Ctrl = new HashSet<Gen_Custom_Seq_Ctrl>();
            this.Gen_Custom_Seq_Ctrl1 = new HashSet<Gen_Custom_Seq_Ctrl>();
            this.Gen_DET_UserPrefer = new HashSet<Gen_DET_UserPrefer>();
            this.Gen_Mst_Appsettings = new HashSet<Gen_Mst_Appsettings>();
            this.Gen_Mst_Appsettings1 = new HashSet<Gen_Mst_Appsettings>();
            this.Gen_Mst_Client = new HashSet<Gen_Mst_Client>();
            this.Gen_Mst_Client1 = new HashSet<Gen_Mst_Client>();
            this.Gen_Mst_ClientMachines = new HashSet<Gen_Mst_ClientMachines>();
            this.Gen_Mst_ClientMachines1 = new HashSet<Gen_Mst_ClientMachines>();
            this.Gen_Mst_DevTraining = new HashSet<Gen_Mst_DevTraining>();
            this.Gen_Mst_DevTraining1 = new HashSet<Gen_Mst_DevTraining>();
            this.Gen_Mst_DocumentType = new HashSet<Gen_Mst_DocumentType>();
            this.Gen_Mst_DocumentType1 = new HashSet<Gen_Mst_DocumentType>();
            this.Gen_Mst_ErrLog = new HashSet<Gen_Mst_ErrLog>();
            this.Gen_Mst_GeneralTestCases = new HashSet<Gen_Mst_GeneralTestCases>();
            this.Gen_Mst_GeneralTestCases1 = new HashSet<Gen_Mst_GeneralTestCases>();
            this.Gen_Mst_Teams = new HashSet<Gen_Mst_Teams>();
            this.Gen_Mst_Teams1 = new HashSet<Gen_Mst_Teams>();
            this.Gen_Mst_Technology = new HashSet<Gen_Mst_Technology>();
            this.Gen_Mst_Technology1 = new HashSet<Gen_Mst_Technology>();
            this.Gen_Mst_TestCaseType = new HashSet<Gen_Mst_TestCaseType>();
            this.Gen_Mst_TestCaseType1 = new HashSet<Gen_Mst_TestCaseType>();
            this.Gen_mst_TestingProcess = new HashSet<Gen_mst_TestingProcess>();
            this.Gen_mst_TestingProcess1 = new HashSet<Gen_mst_TestingProcess>();
            this.Gen_Mst_VersionUpdateDetail = new HashSet<Gen_Mst_VersionUpdateDetail>();
            this.Gen_Mst_VersionUpdateDetail1 = new HashSet<Gen_Mst_VersionUpdateDetail>();
            this.Issue_Defects = new HashSet<Issue_Defects>();
            this.Issue_Defects_History = new HashSet<Issue_Defects_History>();
            this.Issue_Testcases = new HashSet<Issue_Testcases>();
            this.IssueDetails = new HashSet<IssueDetail>();
            this.IssueMasters = new HashSet<IssueMaster>();
            this.IssueMasters1 = new HashSet<IssueMaster>();
            this.IssueMasters2 = new HashSet<IssueMaster>();
            this.IssueMasters3 = new HashSet<IssueMaster>();
            this.IssueMasters4 = new HashSet<IssueMaster>();
            this.IssueMasters5 = new HashSet<IssueMaster>();
            this.IssueMasters6 = new HashSet<IssueMaster>();
            this.IssueMasters7 = new HashSet<IssueMaster>();
            this.Rights_Det_Role_Access = new HashSet<Rights_Det_Role_Access>();
            this.Rights_Det_Role_Access1 = new HashSet<Rights_Det_Role_Access>();
            this.Rights_DET_Role_Actions = new HashSet<Rights_DET_Role_Actions>();
            this.Rights_DET_Role_Actions1 = new HashSet<Rights_DET_Role_Actions>();
            this.Rights_DET_Role_Menu = new HashSet<Rights_DET_Role_Menu>();
            this.Rights_DET_Role_Menu1 = new HashSet<Rights_DET_Role_Menu>();
            this.Rights_DET_User_Actions = new HashSet<Rights_DET_User_Actions>();
            this.Rights_DET_User_Actions1 = new HashSet<Rights_DET_User_Actions>();
            this.Rights_DET_User_Actions2 = new HashSet<Rights_DET_User_Actions>();
            this.Rights_DET_User_Menu = new HashSet<Rights_DET_User_Menu>();
            this.Rights_DET_User_Menu1 = new HashSet<Rights_DET_User_Menu>();
            this.Rights_DET_User_Menu2 = new HashSet<Rights_DET_User_Menu>();
            this.Gen_Mst_VersionUpdate = new HashSet<Gen_Mst_VersionUpdate>();
            this.Gen_Mst_VersionUpdate1 = new HashSet<Gen_Mst_VersionUpdate>();
            this.User_det_DailyTask = new HashSet<User_det_DailyTask>();
            this.User_det_DailyTask1 = new HashSet<User_det_DailyTask>();
        }
    
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string RoleId { get; set; }
        public string TypeId { get; set; }
        public Nullable<bool> LoggedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> SystemUser { get; set; }
        public Nullable<int> AuditRecord { get; set; }
        public string OldPassword { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string BankAccNo { get; set; }
        public Nullable<long> BasicSalary { get; set; }
        public Nullable<long> HRA { get; set; }
        public Nullable<long> Conveyance { get; set; }
        public Nullable<long> EduAllowance { get; set; }
        public Nullable<long> OtherAllowance { get; set; }
        public Nullable<long> Incentives { get; set; }
        public Nullable<long> EmpPF { get; set; }
        public Nullable<long> ESI { get; set; }
        public Nullable<long> TDS { get; set; }
        public Nullable<long> StaffAdvance { get; set; }
        public Nullable<long> Installments { get; set; }
        public Nullable<long> MobileExcess { get; set; }
        public string Bank { get; set; }
        public string EmpCode { get; set; }
        public string OfficeCode { get; set; }
        public Nullable<bool> isresource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Mst_1500Form> Bill_Mst_1500Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Mst_1500Form> Bill_Mst_1500Form1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Mst_Personal> Employee_Mst_Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Mst_Personal> Employee_Mst_Personal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Custom_Number> Gen_Custom_Number { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Custom_Number> Gen_Custom_Number1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Custom_Seq_Ctrl> Gen_Custom_Seq_Ctrl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Custom_Seq_Ctrl> Gen_Custom_Seq_Ctrl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_DET_UserPrefer> Gen_DET_UserPrefer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Appsettings> Gen_Mst_Appsettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Appsettings> Gen_Mst_Appsettings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Client> Gen_Mst_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Client> Gen_Mst_Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_ClientMachines> Gen_Mst_ClientMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_ClientMachines> Gen_Mst_ClientMachines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_DevTraining> Gen_Mst_DevTraining { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_DevTraining> Gen_Mst_DevTraining1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_DocumentType> Gen_Mst_DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_DocumentType> Gen_Mst_DocumentType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_ErrLog> Gen_Mst_ErrLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_GeneralTestCases> Gen_Mst_GeneralTestCases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_GeneralTestCases> Gen_Mst_GeneralTestCases1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Teams> Gen_Mst_Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Teams> Gen_Mst_Teams1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Technology> Gen_Mst_Technology { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_Technology> Gen_Mst_Technology1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_TestCaseType> Gen_Mst_TestCaseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_TestCaseType> Gen_Mst_TestCaseType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_mst_TestingProcess> Gen_mst_TestingProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_mst_TestingProcess> Gen_mst_TestingProcess1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_VersionUpdateDetail> Gen_Mst_VersionUpdateDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_VersionUpdateDetail> Gen_Mst_VersionUpdateDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Defects> Issue_Defects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Defects_History> Issue_Defects_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_Testcases> Issue_Testcases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueDetail> IssueDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueMaster> IssueMasters7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_Det_Role_Access> Rights_Det_Role_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_Det_Role_Access> Rights_Det_Role_Access1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_Role_Actions> Rights_DET_Role_Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_Role_Actions> Rights_DET_Role_Actions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_Role_Menu> Rights_DET_Role_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_Role_Menu> Rights_DET_Role_Menu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_User_Actions> Rights_DET_User_Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_User_Actions> Rights_DET_User_Actions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_User_Actions> Rights_DET_User_Actions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_User_Menu> Rights_DET_User_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_User_Menu> Rights_DET_User_Menu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_User_Menu> Rights_DET_User_Menu2 { get; set; }
        public virtual Rights_MST_Role Rights_MST_Role { get; set; }
        public virtual Rights_MST_UserAccounts Rights_MST_UserAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_VersionUpdate> Gen_Mst_VersionUpdate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Mst_VersionUpdate> Gen_Mst_VersionUpdate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_det_DailyTask> User_det_DailyTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_det_DailyTask> User_det_DailyTask1 { get; set; }
    }
}
