//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights_MST_UserAccounts
    {
        public string UserId { get; set; }
        public bool PassCanChange { get; set; }
        public bool PassCannotChange { get; set; }
        public bool PassNeverExp { get; set; }
        public bool PassAccDisable { get; set; }
        public bool PassChanged { get; set; }
        public bool AccNeverExp { get; set; }
        public Nullable<System.DateTime> AccEndOf { get; set; }
        public Nullable<System.DateTime> PassEndOf { get; set; }
    
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster { get; set; }
    }
}
