//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights_MST_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rights_MST_Role()
        {
            this.Rights_Det_Role_Access = new HashSet<Rights_Det_Role_Access>();
            this.Rights_Det_Role_Access1 = new HashSet<Rights_Det_Role_Access>();
            this.Rights_DET_Role_Actions = new HashSet<Rights_DET_Role_Actions>();
            this.Rights_DET_Role_Menu = new HashSet<Rights_DET_Role_Menu>();
            this.Rights_MST_UserMaster = new HashSet<Rights_MST_UserMaster>();
        }
    
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> SystemRole { get; set; }
        public Nullable<int> auditrecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_Det_Role_Access> Rights_Det_Role_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_Det_Role_Access> Rights_Det_Role_Access1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_Role_Actions> Rights_DET_Role_Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_Role_Menu> Rights_DET_Role_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_MST_UserMaster> Rights_MST_UserMaster { get; set; }
    }
}
