//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights_MST_Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rights_MST_Screen()
        {
            this.Rights_DET_Role_Actions = new HashSet<Rights_DET_Role_Actions>();
            this.Rights_DET_User_Actions = new HashSet<Rights_DET_User_Actions>();
            this.Rights_MST_Action = new HashSet<Rights_MST_Action>();
            this.Rights_MST_Action1 = new HashSet<Rights_MST_Action>();
        }
    
        public string ScreenID { get; set; }
        public string ScreenName { get; set; }
        public string ScreenDesc { get; set; }
        public string MenuId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_Role_Actions> Rights_DET_Role_Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_User_Actions> Rights_DET_User_Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_MST_Action> Rights_MST_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_MST_Action> Rights_MST_Action1 { get; set; }
        public virtual Rights_MST_Menu Rights_MST_Menu { get; set; }
    }
}
