//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights_MST_Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rights_MST_Action()
        {
            this.Rights_DET_Role_Actions = new HashSet<Rights_DET_Role_Actions>();
            this.Rights_DET_User_Actions = new HashSet<Rights_DET_User_Actions>();
        }
    
        public string ActionId { get; set; }
        public string ActionName { get; set; }
        public string ActionDesc { get; set; }
        public string ScreenID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_Role_Actions> Rights_DET_Role_Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rights_DET_User_Actions> Rights_DET_User_Actions { get; set; }
        public virtual Rights_MST_Screen Rights_MST_Screen { get; set; }
        public virtual Rights_MST_Screen Rights_MST_Screen1 { get; set; }
    }
}
