//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sysmz_mst_reports
    {
        public int ReportCode { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string MenuID { get; set; }
        public Nullable<bool> ShowFilter { get; set; }
        public string ReportSPName { get; set; }
        public Nullable<long> ViewColumnCaptionWidth { get; set; }
        public Nullable<long> ViewColumnWidth { get; set; }
    }
}
