//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMZ_Static_Values
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public string DataType { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Comments { get; set; }
        public string SubCode1 { get; set; }
        public string SubCode2 { get; set; }
    }
}
