//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMZ_KeyActions
    {
        public string ActionCode { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> KeyID { get; set; }
    
        public virtual SysMZ_KeyCodes SysMZ_KeyCodes { get; set; }
    }
}
