//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMZ_KeyCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysMZ_KeyCodes()
        {
            this.SysMZ_KeyActions = new HashSet<SysMZ_KeyActions>();
        }
    
        public int KeyID { get; set; }
        public int KeyCode { get; set; }
        public Nullable<int> Shift { get; set; }
        public string KeyCodeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysMZ_KeyActions> SysMZ_KeyActions { get; set; }
    }
}
