//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_det_DailyTask
    {
        public long Rownum { get; set; }
        public Nullable<long> SNO { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.TimeSpan> StartDate { get; set; }
        public Nullable<System.TimeSpan> EndDate { get; set; }
        public Nullable<long> MasterRownum { get; set; }
        public string UserId { get; set; }
        public string Issueno { get; set; }
        public string TaskId { get; set; }
    
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster { get; set; }
        public virtual Rights_MST_UserMaster Rights_MST_UserMaster1 { get; set; }
    }
}
